name: test_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  pansy_ui:
    git:
      url: https://github.com/pansydev/pansy_libraries
      path: packages/pansy_ui

  auto_route: ^3.2.0
  retrofit: ^3.0.1
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  fpdart: ^0.0.12
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  retrofit_generator: ^3.0.1+1
  json_serializable: ^6.1.3
  freezed: ^1.1.0
  dart_code_metrics: ^4.8.1
  index_generator: ^3.0.0
  i18n: ^3.4.1

index_generator:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - initializer.config.dart
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/modules/user/domain
    - path: lib/modules/user/infrastructure
    - path: lib/modules/user/presentation

flutter:
  uses-material-design: true
