name: test_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^4.0.1
  retrofit: ^3.0.1
  json_annotation: ^4.4.0
  freezed_annotation: ^2.0.3
  fpdart: ^0.1.0
  dio_cache_interceptor: ^3.1.0
  path_provider: ^2.0.8
  dio_cache_interceptor_hive_store: ^3.0.2
  flutter_feather_icons: ^2.0.0+1
  form_field_validator: ^1.1.0
  url_launcher: ^6.0.17
  maps_launcher: ^2.0.1
  cached_network_image: ^3.2.0
  dio: ^4.0.6

  flutter_bloc: ^8.0.1
  dino:
    git:
      url: https://github.com/pansydev/dino
      path: packages/dino
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  dino_generator:
    git:
      url: https://github.com/pansydev/dino
      path: packages/dino_generator
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.3
  freezed: ^2.0.3+1
  dart_code_metrics: ^4.8.1
  index_generator: ^3.0.0
  i18n: ^3.4.1
  integration_test:
    sdk: flutter

index_generator:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - initializer.config.dart
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/modules/user/domain
    - path: lib/modules/user/infrastructure
    - path: lib/modules/user/presentation

    - path: lib/modules/photo/domain
    - path: lib/modules/photo/infrastructure
    - path: lib/modules/photo/presentation

    - path: lib/modules/post/domain
    - path: lib/modules/post/infrastructure
    - path: lib/modules/post/presentation

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
          style: italic
